version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static_volume:
